package com.nosferatu.divinemachinerylegacy.client.render;
import com.nosferatu.divinemachinerylegacy.block.BlockMechanicalApothecary;import cpw.mods.fml.client.registry.ISimpleBlockRenderingHandler;import net.minecraft.block.Block;import net.minecraft.client.renderer.RenderBlocks;import net.minecraft.client.renderer.Tessellator;import net.minecraft.init.Blocks;import net.minecraft.util.IIcon;import net.minecraft.world.IBlockAccess;import org.lwjgl.opengl.GL11;import static com.nosferatu.divinemachinerylegacy.client.render.RenderMachineModelUtil.*;
/** Reforked framed Petal Apothecary geometry; never rendered as a cube. */
public class RenderMechanicalApothecary implements ISimpleBlockRenderingHandler{
 private final int id;private static final UV S=new UV(3,1,13,15),TOP=new UV(3,3,13,13),MID=new UV(5,6,11,13);
 public RenderMechanicalApothecary(int i){id=i;}@Override public void renderInventoryBlock(Block b,int m,int model,RenderBlocks r){if(!(b instanceof BlockMechanicalApothecary))return;Tessellator t=Tessellator.instance;GL11.glPushMatrix();GL11.glTranslatef(-.5F,-.5F,-.5F);t.startDrawingQuads();render(t,(BlockMechanicalApothecary)b,m,0,0,0,15728880);t.draw();GL11.glPopMatrix();}@Override public boolean renderWorldBlock(IBlockAccess w,int x,int y,int z,Block b,int model,RenderBlocks r){if(!(b instanceof BlockMechanicalApothecary))return false;render(Tessellator.instance,(BlockMechanicalApothecary)b,w.getBlockMetadata(x,y,z),x,y,z,b.getMixedBrightnessForBlock(w,x,y,z));return true;}
 private static void render(Tessellator t,BlockMechanicalApothecary b,int m,double x,double y,double z,int br){IIcon f=b.getFrameIcon(m),stone=Blocks.cobblestone.getIcon(1,0);frame(t,f,x,y,z,br);box(t,x,y,z,3,1,3,13,2,13,br,stone,TOP,stone,TOP,stone,new UV(3,14,13,15),stone,new UV(3,14,13,15),stone,new UV(3,14,13,15),stone,new UV(3,14,13,15));box(t,x,y,z,5,2,5,11,9,11,br,null,null,null,null,stone,MID,stone,MID,stone,MID,stone,MID);box(t,x,y,z,3,9,3,13,10,13,br,stone,TOP,stone,TOP,stone,new UV(3,4,13,5),stone,new UV(3,4,13,5),stone,new UV(3,4,13,5),stone,new UV(3,4,13,5));box(t,x,y,z,3,10,12,13,13,13,br,null,null,stone,new UV(3,12,13,13),stone,S,stone,S,stone,new UV(12,1,13,4),stone,new UV(3,1,4,4));box(t,x,y,z,3,10,3,13,13,4,br,null,null,stone,new UV(3,3,13,4),stone,S,stone,S,stone,new UV(3,1,4,4),stone,new UV(12,1,13,4));box(t,x,y,z,3,10,4,4,13,12,br,null,null,stone,new UV(3,4,4,12),null,null,null,null,stone,new UV(4,1,12,4),stone,new UV(4,1,12,4));box(t,x,y,z,12,10,4,13,13,12,br,null,null,stone,new UV(12,4,13,12),null,null,null,null,stone,new UV(4,1,12,4),stone,new UV(4,1,12,4));}
 @Override public boolean shouldRender3DInInventory(int i){return true;}@Override public int getRenderId(){return id;}
}
