package com.nosferatu.divinemachinerylegacy.gui;
import com.nosferatu.divinemachinerylegacy.DivineMachineryLegacy;import com.nosferatu.divinemachinerylegacy.botania.MachineTier;import com.nosferatu.divinemachinerylegacy.tile.TileMechanicalApothecary;import net.minecraft.entity.player.EntityPlayer;import net.minecraft.entity.player.InventoryPlayer;import net.minecraft.inventory.*;import net.minecraft.item.ItemStack;
public class ContainerMechanicalApothecary extends Container{
 private static final int H=-1000;private final TileMechanicalApothecary tile;private int lw=Integer.MIN_VALUE,lp=Integer.MIN_VALUE,lb=Integer.MIN_VALUE;private int cw,cp,cb;
 public ContainerMechanicalApothecary(InventoryPlayer p,TileMechanicalApothecary t){tile=t;MachineTier tier=t.getTier();addSlotToContainer(new Valid(t,0,90,79));for(int i=0;i<2;i++)addSlotToContainer(new Valid(t,1+i,i<t.getUpgradeSlots()?90+i*20:H,i<t.getUpgradeSlots()?100:H));int inputs=t.getInputCount();for(int i=0;i<16;i++){int[] q=coord(tier,i,true);addSlotToContainer(new Valid(t,TileMechanicalApothecary.SLOT_INPUT_START+i,i<inputs?q[0]:H,i<inputs?q[1]:H));}int outputs=t.getOutputCount();for(int i=0;i<16;i++){int[] q=coord(tier,i,false);addSlotToContainer(new Out(t,TileMechanicalApothecary.SLOT_OUTPUT_START+i,i<outputs?q[0]:H,i<outputs?q[1]:H));}for(int r=0;r<3;r++)for(int c=0;c<9;c++)addSlotToContainer(new Slot(p,c+r*9+9,28+c*18,148+r*18));for(int c=0;c<9;c++)addSlotToContainer(new Slot(p,c,28+c*18,206));}
 private static int[] coord(MachineTier t,int i,boolean in){int cols=t==MachineTier.MALACHITE?3:(t==MachineTier.SAFFRON?3:4);int x=in?(t==MachineTier.CRIMSON?24:30):(t==MachineTier.CRIMSON?124:114);int y=t==MachineTier.MALACHITE?28:19;return new int[]{x+(i%cols)*18,y+(i/cols)*18};}
 @Override public boolean canInteractWith(EntityPlayer p){return tile.isUseableByPlayer(p);}@Override public void detectAndSendChanges(){super.detectAndSendChanges();int w=tile.getWater(),pr=tile.getProgress(),b=tile.getBatch();for(Object o:crafters){ICrafting c=(ICrafting)o;if(w!=lw){c.sendProgressBarUpdate(this,0,w&65535);c.sendProgressBarUpdate(this,1,w>>>16);}if(pr!=lp)c.sendProgressBarUpdate(this,2,pr);if(b!=lb)c.sendProgressBarUpdate(this,3,b);}lw=w;lp=pr;lb=b;}@Override public void updateProgressBar(int id,int v){int u=v&65535;if(id==0){cw=(cw&0xffff0000)|u;tile.setClientWater(cw);}else if(id==1){cw=(cw&0xffff)|(u<<16);tile.setClientWater(cw);}else if(id==2){cp=u;tile.setClientProgress(cp);}else if(id==3){cb=u;tile.setClientBatch(cb);}}
 @Override public ItemStack transferStackInSlot(EntityPlayer p,int i){ItemStack orig=null;Slot s=(Slot)inventorySlots.get(i);if(s==null||!s.getHasStack())return null;ItemStack st=s.getStack();orig=st.copy();int machine=35;if(i<machine){if(!mergeItemStack(st,machine,inventorySlots.size(),true))return null;}else{boolean moved=false;for(int slot=0;slot<machine&&!moved;slot++)if(tile.isItemValidForSlot(slot,st))moved=mergeItemStack(st,slot,slot+1,false);if(!moved)return null;}if(st.stackSize==0)s.putStack(null);else s.onSlotChanged();return orig;}
 private static class Valid extends Slot{Valid(TileMechanicalApothecary t,int i,int x,int y){super(t,i,x,y);}@Override public boolean isItemValid(ItemStack s){return inventory.isItemValidForSlot(getSlotIndex(),s);}}private static class Out extends Slot{Out(TileMechanicalApothecary t,int i,int x,int y){super(t,i,x,y);}@Override public boolean isItemValid(ItemStack s){return false;}}
}
