package com.nosferatu.divinemachinerylegacy.block;
import com.nosferatu.divinemachinerylegacy.DivineMachineryLegacy;import com.nosferatu.divinemachinerylegacy.botania.MachineTier;import com.nosferatu.divinemachinerylegacy.tile.TileMechanicalDaisy;import cpw.mods.fml.relauncher.Side;import cpw.mods.fml.relauncher.SideOnly;import net.minecraft.block.Block;import net.minecraft.block.BlockContainer;import net.minecraft.block.material.Material;import net.minecraft.client.renderer.texture.IIconRegister;import net.minecraft.entity.item.EntityItem;import net.minecraft.entity.player.EntityPlayer;import net.minecraft.inventory.IInventory;import net.minecraft.item.Item;import net.minecraft.item.ItemStack;import net.minecraft.tileentity.TileEntity;import net.minecraft.util.IIcon;import net.minecraft.world.World;import java.util.List;
public class BlockMechanicalDaisy extends BlockContainer{
 private static int renderId;@SideOnly(Side.CLIENT)private IIcon[] plates;@SideOnly(Side.CLIENT)private IIcon flower;
 public BlockMechanicalDaisy(){super(Material.rock);setBlockName(DivineMachineryLegacy.MODID+".mechanical_daisy");setHardness(3F);setResistance(8F);setLightOpacity(0);setCreativeTab(DivineMachineryLegacy.CREATIVE_TAB);setBlockBounds(0,0,0,1,.72F,1);}
 public static void setRenderId(int i){renderId=i;}@Override public int getRenderType(){return renderId;}@Override public boolean isOpaqueCube(){return false;}@Override public boolean renderAsNormalBlock(){return false;}@Override public TileEntity createNewTileEntity(World w,int m){return new TileMechanicalDaisy();}@Override public int damageDropped(int m){return m&3;}@Override protected ItemStack createStackedBlock(int m){return new ItemStack(this,1,m&3);}@Override @SideOnly(Side.CLIENT)public void getSubBlocks(Item i,net.minecraft.creativetab.CreativeTabs t,List l){for(int m=0;m<4;m++)l.add(new ItemStack(i,1,m));}
 @Override @SideOnly(Side.CLIENT)public void registerBlockIcons(IIconRegister r){plates=new IIcon[]{r.registerIcon(DivineMachineryLegacy.MODID+":reforked/malachite_dragonstone_block"),r.registerIcon(DivineMachineryLegacy.MODID+":reforked/saffron_dragonstone_block"),r.registerIcon(DivineMachineryLegacy.MODID+":reforked/shadow_dragonstone_block"),r.registerIcon(DivineMachineryLegacy.MODID+":reforked/crimson_dragonstone_block")};flower=r.registerIcon("Botania:pureDaisy");blockIcon=plates[0];}@Override @SideOnly(Side.CLIENT)public IIcon getIcon(int s,int m){return getPlate(m);}@SideOnly(Side.CLIENT)public IIcon getPlate(int m){return plates[MachineTier.fromMeta(m).ordinal()];}@SideOnly(Side.CLIENT)public IIcon getFlower(){return flower;}
 @Override public boolean onBlockActivated(World w,int x,int y,int z,EntityPlayer p,int s,float a,float b,float c){if(!w.isRemote)p.openGui(DivineMachineryLegacy.INSTANCE,DivineMachineryLegacy.GUI_DAISY,w,x,y,z);return true;}@Override public void breakBlock(World w,int x,int y,int z,Block b,int m){TileEntity te=w.getTileEntity(x,y,z);if(te instanceof IInventory){IInventory q=(IInventory)te;for(int i=0;i<q.getSizeInventory();i++){ItemStack st=q.getStackInSlot(i);if(st!=null)w.spawnEntityInWorld(new EntityItem(w,x+.5,y+.5,z+.5,st.copy()));}}super.breakBlock(w,x,y,z,b,m);}
}
