package com.nosferatu.divinemachinerylegacy.tile;
import appeng.api.implementations.tiles.ICraftingMachine;import appeng.api.networking.crafting.ICraftingPatternDetails;import com.nosferatu.divinemachinerylegacy.DivineMachineryLegacy;import com.nosferatu.divinemachinerylegacy.botania.MachineTier;import net.minecraft.block.Block;import net.minecraft.entity.player.EntityPlayer;import net.minecraft.init.Blocks;import net.minecraft.inventory.ISidedInventory;import net.minecraft.inventory.InventoryCrafting;import net.minecraft.item.Item;import net.minecraft.item.ItemStack;import net.minecraft.nbt.NBTTagCompound;import net.minecraft.nbt.NBTTagList;import net.minecraft.tileentity.TileEntity;import net.minecraftforge.common.util.Constants;import net.minecraftforge.common.util.ForgeDirection;import net.minecraftforge.fluids.*;import vazkii.botania.api.BotaniaAPI;import vazkii.botania.api.recipe.RecipePureDaisy;import java.util.Arrays;
/** Eight-slot internal Pure Daisy processor matching Extra Reforked's machine form. */
public class TileMechanicalDaisy extends TileEntity implements ISidedInventory,IFluidHandler,ICraftingMachine{
 public static final int SLOT_UPGRADE=0,SLOT_WORK_START=1,SLOT_WORK_END=8,INVENTORY_SIZE=9;private final ItemStack[] inv=new ItemStack[INVENTORY_SIZE];private final int[] ticks=new int[8];private final boolean[] done=new boolean[8];private int water,waterTicks;private boolean internal;
 @Override public void updateEntity(){if(worldObj==null||worldObj.isRemote)return;refillInfinite();for(int i=0;i<8;i++)tickSlot(i);tickSnow();}
 private void tickSlot(int i){int slot=SLOT_WORK_START+i;ItemStack s=inv[slot];if(s==null){ticks[i]=0;done[i]=false;return;}if(done[i])return;RecipePureDaisy r=find(s);if(r==null){ticks[i]=0;return;}ticks[i]++;if(ticks[i]>=1200){int count=s.stackSize;inv[slot]=new ItemStack(r.getOutput(),count,r.getOutputMeta());done[i]=true;ticks[i]=0;markDirty();}}
 private RecipePureDaisy find(ItemStack s){Block b=Block.getBlockFromItem(s.getItem());if(b==Blocks.air)return null;for(RecipePureDaisy r:BotaniaAPI.pureDaisyRecipes)if(r.matches(worldObj,xCoord,yCoord,zCoord,null,b,s.getItemDamage()))return r;return null;}
 private void refillInfinite(){if(getTier()!=MachineTier.CRIMSON)return;ItemStack up=inv[SLOT_UPGRADE];if(up==null)return;Block source=null;if(up.getItem()==DivineMachineryLegacy.catalystStoneInfinity)source=Blocks.stone;else if(up.getItem()==DivineMachineryLegacy.catalystWoodInfinity)source=Blocks.log;if(source==null)return;for(int i=0;i<8;i++){int s=SLOT_WORK_START+i;if(inv[s]==null){inv[s]=new ItemStack(source,getSlotLimit(),0);done[i]=false;ticks[i]=0;}}}
 private void tickSnow(){if(water<1000)return;if(++waterTicks<200)return;waterTicks=0;int mult=getTier()==MachineTier.MALACHITE?2:getTier()==MachineTier.SAFFRON?4:getTier()==MachineTier.SHADOW?8:16;for(int i=0;i<8&&water>=1000;i++){int slot=SLOT_WORK_START+i;ItemStack s=inv[slot];if(s==null){int q=Math.min(mult,getSlotLimit());inv[slot]=new ItemStack(Blocks.snow,q);done[i]=true;water-=1000*q;}else if(s.getItem()==Item.getItemFromBlock(Blocks.snow)){int q=Math.min(mult,getSlotLimit()-s.stackSize);q=Math.min(q,water/1000);if(q>0){s.stackSize+=q;water-=1000*q;done[i]=true;}}}markDirty();}
 public MachineTier getTier(){return worldObj==null?MachineTier.MALACHITE:MachineTier.fromMeta(worldObj.getBlockMetadata(xCoord,yCoord,zCoord));}public int getSlotLimit(){return getTier()==MachineTier.MALACHITE?4:getTier()==MachineTier.SAFFRON?8:getTier()==MachineTier.SHADOW?16:32;}public int getWaterCapacity(){return getTier()==MachineTier.MALACHITE?16000:getTier()==MachineTier.SAFFRON?32000:getTier()==MachineTier.SHADOW?64000:128000;}public int getWater(){return water;}public int getProgress(int i){return i>=0&&i<8?ticks[i]:0;}public boolean hasUpgradeSlot(){return getTier()==MachineTier.CRIMSON;}
 private boolean isUpgrade(ItemStack s){return s!=null&&(s.getItem()==DivineMachineryLegacy.catalystStoneInfinity||s.getItem()==DivineMachineryLegacy.catalystWoodInfinity);}private boolean validBlock(ItemStack s){return find(s)!=null||s!=null&&s.getItem()==Item.getItemFromBlock(Blocks.snow);}
 @Override public boolean acceptsPlans(){return true;}@Override public boolean pushPattern(ICraftingPatternDetails p,InventoryCrafting t,ForgeDirection d){if(worldObj==null||worldObj.isRemote||p==null||p.isCraftable())return false;ItemStack[] cp=copy();for(int i=0;i<t.getSizeInventory();i++){ItemStack s=t.getStackInSlot(i);if(s==null)continue;if(!validBlock(s)||!insert(cp,s.copy()))return false;}internal=true;try{for(int i=0;i<t.getSizeInventory();i++){ItemStack s=t.getStackInSlot(i);if(s!=null)insert(inv,s.copy());}}finally{internal=false;}markDirty();return true;}
 private ItemStack[] copy(){ItemStack[] c=new ItemStack[INVENTORY_SIZE];for(int i=0;i<c.length;i++)c[i]=inv[i]==null?null:inv[i].copy();return c;}private boolean insert(ItemStack[] a,ItemStack x){int left=x.stackSize;for(int i=SLOT_WORK_START;i<=SLOT_WORK_END&&left>0;i++){ItemStack e=a[i];if(e!=null&&!done[i-1]&&e.isItemEqual(x)){int room=getSlotLimit()-e.stackSize;int m=Math.min(room,left);e.stackSize+=m;left-=m;}}for(int i=SLOT_WORK_START;i<=SLOT_WORK_END&&left>0;i++)if(a[i]==null){ItemStack q=x.copy();q.stackSize=Math.min(left,getSlotLimit());a[i]=q;left-=q.stackSize;}return left==0;}
 @Override public int fill(ForgeDirection f,FluidStack r,boolean d){if(r==null||r.getFluid()!=FluidRegistry.WATER)return 0;int a=Math.min(r.amount,getWaterCapacity()-water);if(d&&a>0){water+=a;markDirty();}return a;}@Override public FluidStack drain(ForgeDirection f,FluidStack r,boolean d){return r!=null&&r.getFluid()==FluidRegistry.WATER?drain(f,r.amount,d):null;}@Override public FluidStack drain(ForgeDirection f,int m,boolean d){int a=Math.min(m,water);if(a<=0)return null;if(d){water-=a;markDirty();}return new FluidStack(FluidRegistry.WATER,a);}@Override public boolean canFill(ForgeDirection f,Fluid q){return q==FluidRegistry.WATER;}@Override public boolean canDrain(ForgeDirection f,Fluid q){return q==FluidRegistry.WATER;}@Override public FluidTankInfo[] getTankInfo(ForgeDirection f){return new FluidTankInfo[]{new FluidTankInfo(new FluidStack(FluidRegistry.WATER,water),getWaterCapacity())};}
 @Override public int getSizeInventory(){return INVENTORY_SIZE;}@Override public ItemStack getStackInSlot(int i){return i>=0&&i<INVENTORY_SIZE?inv[i]:null;}@Override public ItemStack decrStackSize(int i,int a){ItemStack s=getStackInSlot(i);if(s==null)return null;ItemStack r;if(s.stackSize<=a){r=s;inv[i]=null;}else r=s.splitStack(a);changed(i);return r;}@Override public ItemStack getStackInSlotOnClosing(int i){ItemStack s=getStackInSlot(i);inv[i]=null;changed(i);return s;}@Override public void setInventorySlotContents(int i,ItemStack s){inv[i]=s;if(s!=null&&i>0&&s.stackSize>getSlotLimit())s.stackSize=getSlotLimit();changed(i);}@Override public String getInventoryName(){return "container.divinemachinerylegacy.daisy";}@Override public boolean hasCustomInventoryName(){return false;}@Override public int getInventoryStackLimit(){return 32;}@Override public boolean isUseableByPlayer(EntityPlayer p){return worldObj!=null&&worldObj.getTileEntity(xCoord,yCoord,zCoord)==this&&p.getDistanceSq(xCoord+.5,yCoord+.5,zCoord+.5)<=64;}@Override public void openInventory(){}@Override public void closeInventory(){}@Override public boolean isItemValidForSlot(int i,ItemStack s){if(i==SLOT_UPGRADE)return hasUpgradeSlot()&&isUpgrade(s);return i>=SLOT_WORK_START&&i<=SLOT_WORK_END&&!done[i-1]&&validBlock(s);}@Override public int[] getAccessibleSlotsFromSide(int side){int[] a=new int[hasUpgradeSlot()?9:8];int p=0;if(hasUpgradeSlot())a[p++]=0;for(int i=1;i<=8;i++)a[p++]=i;return a;}@Override public boolean canInsertItem(int i,ItemStack s,int side){return getStackInSlot(i)==null&&isItemValidForSlot(i,s);}@Override public boolean canExtractItem(int i,ItemStack s,int side){return i>=1&&i<=8&&done[i-1];}
 private void changed(int i){if(!internal&&i>=1&&i<=8){ticks[i-1]=0;done[i-1]=false;}markDirty();}
 @Override public void writeToNBT(NBTTagCompound n){super.writeToNBT(n);n.setInteger("water",water);n.setIntArray("ticks",ticks);int mask=0;for(int i=0;i<8;i++)if(done[i])mask|=1<<i;n.setInteger("done",mask);NBTTagList l=new NBTTagList();for(int i=0;i<inv.length;i++)if(inv[i]!=null){NBTTagCompound c=new NBTTagCompound();c.setByte("slot",(byte)i);inv[i].writeToNBT(c);l.appendTag(c);}n.setTag("inv",l);}@Override public void readFromNBT(NBTTagCompound n){super.readFromNBT(n);water=n.getInteger("water");int[] a=n.getIntArray("ticks");System.arraycopy(a,0,ticks,0,Math.min(8,a.length));int mask=n.getInteger("done");for(int i=0;i<8;i++)done[i]=(mask&(1<<i))!=0;Arrays.fill(inv,null);NBTTagList l=n.getTagList("inv",Constants.NBT.TAG_COMPOUND);for(int j=0;j<l.tagCount();j++){NBTTagCompound c=l.getCompoundTagAt(j);int i=c.getByte("slot")&255;if(i<inv.length)inv[i]=ItemStack.loadItemStackFromNBT(c);}}
 public void setClientWater(int v){if(worldObj!=null&&worldObj.isRemote)water=v;}
}
