package com.nosferatu.divinemachinerylegacy.tile;

import appeng.api.implementations.tiles.ICraftingMachine;import appeng.api.networking.crafting.ICraftingPatternDetails;
import com.nosferatu.divinemachinerylegacy.DivineMachineryLegacy;import com.nosferatu.divinemachinerylegacy.botania.MachineTier;
import net.minecraft.entity.player.EntityPlayer;import net.minecraft.inventory.ISidedInventory;import net.minecraft.inventory.InventoryCrafting;import net.minecraft.item.Item;import net.minecraft.item.ItemStack;import net.minecraft.nbt.NBTTagCompound;import net.minecraft.nbt.NBTTagList;import net.minecraft.tileentity.TileEntity;import net.minecraftforge.common.util.Constants;import net.minecraftforge.common.util.ForgeDirection;import net.minecraftforge.fluids.*;import net.minecraftforge.oredict.OreDictionary;import vazkii.botania.api.BotaniaAPI;import vazkii.botania.api.recipe.RecipePetals;
import java.util.*;

/** Inventory/fluid automation port of Extra Reforked's Mechanical Apothecary. */
public class TileMechanicalApothecary extends TileEntity implements ISidedInventory,IFluidHandler,ICraftingMachine{
 public static final int SLOT_SEEDS=0,SLOT_UPGRADE_START=1,SLOT_UPGRADE_END=2,SLOT_INPUT_START=3,SLOT_INPUT_END=18,SLOT_OUTPUT_START=19,SLOT_OUTPUT_END=34,INVENTORY_SIZE=35;
 private final ItemStack[] inv=new ItemStack[INVENTORY_SIZE]; private int water,progress,batch; private RecipePetals recipe; private boolean internal;
 @Override public void updateEntity(){if(worldObj==null||worldObj.isRemote)return;if(recipe==null)findRecipe();if(recipe==null)return;if(!requirementsStillPresent()){reset();return;}if(++progress>=20)craft();markDirty();}
 private void findRecipe(){for(RecipePetals r:BotaniaAPI.petalRecipes){for(int b=getTier().getParallelCrafts();b>=1;b--){Plan p=plan(r,b);if(p==null)continue;if(!hasInfiniteSeeds()&&seedCount()<b)continue;if(!hasInfiniteWater()&&water<1000*b)continue;ItemStack out=r.getOutput();if(out==null||!canFit(out,b))continue;recipe=r;batch=b;progress=0;return;}}}
 private boolean requirementsStillPresent(){return recipe!=null&&batch>0&&plan(recipe,batch)!=null&&(hasInfiniteSeeds()||seedCount()>=batch)&&(hasInfiniteWater()||water>=1000*batch)&&canFit(recipe.getOutput(),batch);}
 private Plan plan(RecipePetals r,int b){int n=getInputCount(),first=SLOT_INPUT_START;int[] avail=new int[n],use=new int[n];for(int i=0;i<n;i++){ItemStack s=inv[first+i];avail[i]=s==null?0:s.stackSize;}for(int c=0;c<b;c++)for(Object req:r.getInputs()){int found=-1;for(int i=0;i<n;i++)if(avail[i]>0&&matches(req,inv[first+i])){found=i;break;}if(found<0)return null;avail[found]--;use[found]++;}return new Plan(use);}
 private boolean matches(Object req,ItemStack s){if(s==null)return false;if(req instanceof ItemStack){ItemStack w=(ItemStack)req;return w.getItem()==s.getItem()&&(w.getItemDamage()==s.getItemDamage()||w.getItemDamage()==OreDictionary.WILDCARD_VALUE);}if(req instanceof String){for(ItemStack o:OreDictionary.getOres((String)req))if(OreDictionary.itemMatches(o,s,false))return true;}return false;}
 private void craft(){Plan p=plan(recipe,batch);if(p==null){reset();return;}internal=true;try{for(int i=0;i<p.use.length;i++){int a=p.use[i];if(a<=0)continue;ItemStack s=inv[SLOT_INPUT_START+i];s.stackSize-=a;if(s.stackSize<=0)inv[SLOT_INPUT_START+i]=null;}if(!hasInfiniteSeeds())consumeSeeds(batch);if(!hasInfiniteWater())water=Math.max(0,water-1000*batch);ItemStack out=recipe.getOutput().copy();out.stackSize*=batch;insertOutput(out);}finally{internal=false;}worldObj.playSoundEffect(xCoord+.5,yCoord+.5,zCoord+.5,"botania:altarCraft",1F,1F);reset();markDirty();}
 private void consumeSeeds(int a){ItemStack s=inv[SLOT_SEEDS];if(s!=null){s.stackSize-=a;if(s.stackSize<=0)inv[SLOT_SEEDS]=null;}}
 private int seedCount(){ItemStack s=inv[SLOT_SEEDS];return s==null?0:s.stackSize;}
 private boolean canFit(ItemStack out,int b){ItemStack[] cp=copy();ItemStack x=out.copy();x.stackSize*=b;return insert(cp,x,SLOT_OUTPUT_START,getLastOutput());}
 private void insertOutput(ItemStack x){insert(inv,x,SLOT_OUTPUT_START,getLastOutput());}
 private boolean insert(ItemStack[] a,ItemStack x,int f,int l){int left=x.stackSize;for(int i=f;i<=l&&left>0;i++){ItemStack e=a[i];if(e!=null&&e.isItemEqual(x)&&ItemStack.areItemStackTagsEqual(e,x)){int room=Math.min(e.getMaxStackSize(),64)-e.stackSize;int m=Math.min(room,left);e.stackSize+=m;left-=m;}}for(int i=f;i<=l&&left>0;i++)if(a[i]==null){ItemStack q=x.copy();q.stackSize=Math.min(left,q.getMaxStackSize());a[i]=q;left-=q.stackSize;}return left==0;}
 private ItemStack[] copy(){ItemStack[] c=new ItemStack[INVENTORY_SIZE];for(int i=0;i<c.length;i++)c[i]=inv[i]==null?null:inv[i].copy();return c;}
 private void reset(){recipe=null;batch=0;progress=0;}
 public MachineTier getTier(){return worldObj==null?MachineTier.MALACHITE:MachineTier.fromMeta(worldObj.getBlockMetadata(xCoord,yCoord,zCoord));}
 public int getInputCount(){switch(getTier()){case SAFFRON:return 12;case SHADOW:case CRIMSON:return 16;default:return 9;}}
 public int getOutputCount(){return getInputCount();} private int getLastOutput(){return SLOT_OUTPUT_START+getOutputCount()-1;}
 public int getWaterCapacity(){switch(getTier()){case SAFFRON:return 32000;case SHADOW:return 64000;case CRIMSON:return 128000;default:return 16000;}}
 public int getWater(){return water;}public int getProgress(){return progress;}public int getBatch(){return batch;}
 public int getUpgradeSlots(){return getTier().getUpgradeSlots();}
 private boolean hasUpgrade(Item item){for(int i=0;i<getUpgradeSlots();i++){ItemStack s=inv[SLOT_UPGRADE_START+i];if(s!=null&&s.getItem()==item)return true;}return false;}
 public boolean hasInfiniteSeeds(){return hasUpgrade(DivineMachineryLegacy.catalystSeedInfinity);}public boolean hasInfiniteWater(){return hasUpgrade(DivineMachineryLegacy.catalystWaterInfinity);}
 private boolean isUpgrade(ItemStack s){return s!=null&&(s.getItem()==DivineMachineryLegacy.catalystSeedInfinity||s.getItem()==DivineMachineryLegacy.catalystWaterInfinity);}
 private boolean isSeed(ItemStack s){if(s==null)return false;for(int id:OreDictionary.getOreIDs(s))if(OreDictionary.getOreName(id).toLowerCase(Locale.ENGLISH).startsWith("seed"))return true;String n=s.getUnlocalizedName();return n!=null&&n.toLowerCase(Locale.ENGLISH).contains("seed");}
 private boolean validInput(ItemStack s){for(RecipePetals r:BotaniaAPI.petalRecipes)for(Object o:r.getInputs())if(matches(o,s))return true;return false;}
 @Override public boolean acceptsPlans(){return true;}@Override public boolean pushPattern(ICraftingPatternDetails p,InventoryCrafting t,ForgeDirection d){if(worldObj==null||worldObj.isRemote||p==null||p.isCraftable())return false;ItemStack[] cp=copy();for(int i=0;i<t.getSizeInventory();i++){ItemStack s=t.getStackInSlot(i);if(s==null)continue;if(!validInput(s)||!insert(cp,s.copy(),SLOT_INPUT_START,SLOT_INPUT_START+getInputCount()-1))return false;}internal=true;try{for(int i=0;i<t.getSizeInventory();i++){ItemStack s=t.getStackInSlot(i);if(s!=null)insert(inv,s.copy(),SLOT_INPUT_START,SLOT_INPUT_START+getInputCount()-1);}}finally{internal=false;}reset();markDirty();return true;}
 @Override public int fill(ForgeDirection from,FluidStack r,boolean doFill){if(r==null||r.getFluid()!=FluidRegistry.WATER)return 0;int a=Math.min(r.amount,getWaterCapacity()-water);if(doFill&&a>0){water+=a;markDirty();}return a;}@Override public FluidStack drain(ForgeDirection f,FluidStack r,boolean d){if(r==null||r.getFluid()!=FluidRegistry.WATER)return null;return drain(f,r.amount,d);}@Override public FluidStack drain(ForgeDirection f,int m,boolean d){int a=Math.min(m,water);if(a<=0)return null;if(d){water-=a;markDirty();}return new FluidStack(FluidRegistry.WATER,a);}@Override public boolean canFill(ForgeDirection f,Fluid fluid){return fluid==FluidRegistry.WATER;}@Override public boolean canDrain(ForgeDirection f,Fluid fluid){return fluid==FluidRegistry.WATER;}@Override public FluidTankInfo[] getTankInfo(ForgeDirection f){return new FluidTankInfo[]{new FluidTankInfo(new FluidStack(FluidRegistry.WATER,water),getWaterCapacity())};}
 @Override public int getSizeInventory(){return INVENTORY_SIZE;}@Override public ItemStack getStackInSlot(int i){return i>=0&&i<INVENTORY_SIZE?inv[i]:null;}@Override public ItemStack decrStackSize(int i,int a){ItemStack s=getStackInSlot(i);if(s==null)return null;ItemStack r=s.stackSize<=a?s:s.splitStack(a);if(s.stackSize<=a||s.stackSize<=0)inv[i]=null;changed(i);return r;}@Override public ItemStack getStackInSlotOnClosing(int i){ItemStack s=getStackInSlot(i);inv[i]=null;changed(i);return s;}@Override public void setInventorySlotContents(int i,ItemStack s){inv[i]=s;if(s!=null&&s.stackSize>64)s.stackSize=64;changed(i);}@Override public String getInventoryName(){return "container.divinemachinerylegacy.apothecary";}@Override public boolean hasCustomInventoryName(){return false;}@Override public int getInventoryStackLimit(){return 64;}@Override public boolean isUseableByPlayer(EntityPlayer p){return worldObj!=null&&worldObj.getTileEntity(xCoord,yCoord,zCoord)==this&&p.getDistanceSq(xCoord+.5,yCoord+.5,zCoord+.5)<=64;}@Override public void openInventory(){}@Override public void closeInventory(){}
 @Override public boolean isItemValidForSlot(int i,ItemStack s){if(i==SLOT_SEEDS)return isSeed(s);if(i>=SLOT_UPGRADE_START&&i<=SLOT_UPGRADE_END)return i-SLOT_UPGRADE_START<getUpgradeSlots()&&isUpgrade(s);if(i>=SLOT_INPUT_START&&i<SLOT_INPUT_START+getInputCount())return validInput(s);return false;}@Override public int[] getAccessibleSlotsFromSide(int side){int[] a=new int[1+getUpgradeSlots()+getInputCount()+getOutputCount()];int p=0;a[p++]=SLOT_SEEDS;for(int i=0;i<getUpgradeSlots();i++)a[p++]=SLOT_UPGRADE_START+i;for(int i=0;i<getInputCount();i++)a[p++]=SLOT_INPUT_START+i;for(int i=0;i<getOutputCount();i++)a[p++]=SLOT_OUTPUT_START+i;return a;}@Override public boolean canInsertItem(int i,ItemStack s,int side){return isItemValidForSlot(i,s);}@Override public boolean canExtractItem(int i,ItemStack s,int side){return i>=SLOT_OUTPUT_START&&i<=getLastOutput();}
 private void changed(int i){if(!internal&&i<SLOT_OUTPUT_START)reset();markDirty();}
 @Override public void writeToNBT(NBTTagCompound n){super.writeToNBT(n);n.setInteger("water",water);n.setInteger("progress",progress);NBTTagList l=new NBTTagList();for(int i=0;i<inv.length;i++)if(inv[i]!=null){NBTTagCompound c=new NBTTagCompound();c.setByte("slot",(byte)i);inv[i].writeToNBT(c);l.appendTag(c);}n.setTag("inv",l);}
 @Override public void readFromNBT(NBTTagCompound n){super.readFromNBT(n);water=n.getInteger("water");progress=n.getInteger("progress");Arrays.fill(inv,null);NBTTagList l=n.getTagList("inv",Constants.NBT.TAG_COMPOUND);for(int j=0;j<l.tagCount();j++){NBTTagCompound c=l.getCompoundTagAt(j);int i=c.getByte("slot")&255;if(i<inv.length)inv[i]=ItemStack.loadItemStackFromNBT(c);}reset();}
 public void setClientWater(int v){if(worldObj!=null&&worldObj.isRemote)water=v;}public void setClientProgress(int v){if(worldObj!=null&&worldObj.isRemote)progress=v;}public void setClientBatch(int v){if(worldObj!=null&&worldObj.isRemote)batch=v;}
 private static final class Plan{final int[] use;Plan(int[] u){use=u;}}
}
